#!/usr/bin/env python3


#Python script that lists all databases in MongoDB.
from pymongo import MongoClient

# Connect to MongoDB server
client = MongoClient('mongodb://localhost:27017/')

# List all databases
databases = client.list_database_names()

# Print the list of databases
for db in databases:
    print(db)

